
spring.application.name=tp16
server.port=8082


management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

management.endpoint.health.show-details=always
management.endpoint.health.enabled=true

management.endpoint.metrics.enabled=true

management.endpoint.info.enabled=true
management.info.env.enabled=true

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

info.app.name=TP16 Monitoring App
info.app.version=1.0.0
info.app.description=TP16 - Supervision et Logging Spring Boot
info.app.author=EnsembleEtudiants
info.app.java.version=${java.version}

logging.level.root=INFO

logging.level.ma.ens.tp16=DEBUG

logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO

logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.file.total-size-cap=100MB

logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n


management.metrics.distribution.percentiles-histogram.http.server.requests=true

management.metrics.tags.application=${spring.application.name}
management.metrics.tags.environment=development


spring.output.ansi.enabled=always
